class "cheat_menu"  (CUIScriptWnd)

local type_by_index = {"weapons","ammo","addons","outfits","artefacts","items","quest_items","unique"}
function cheat_menu:__init(owner) super()
	if self.menu_index == nil then self.menu_index = 1 end
	local eng = [[qwertyuiop[]asdfghjkl;'zxcvbnm,./QWERTYUIOP{}ASDFGHJKL:"ZXCVBNM<>?!@#$%^&*()-_+=\| 0123456789]]
	local rus = [[йцукенгшщзхъфывапролджэячсмитьбю.ЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ,!"№;%:?*()-_+=\/ 0123456789]]
	self.translit = {}
	for i = 1, string.len(rus) do
		self.translit[string.sub(eng, i, i)] = string.sub(rus, i, i)
	end
	self:InitControls()
	self:InitCallBacks()
	self:FillList()
end

function cheat_menu:__finalize()
end

function cheat_menu:FillList()
	if self.list:GetSize() > 0 then self.list:RemoveAll() end
	self.tbl = ui_cheat_main.cheat_list[type_by_index[self.menu_index]]
	for i = 1,#(self.tbl) do
		local item = self.tbl[i]
		self:AddItemToList(item)
	end
end

function cheat_menu:InitControls()
	self:Init(0,0, 1024, 768)
	local xml = CScriptXmlInit()
	xml:ParseFile("ui_cheat_soc.xml")
	xml:InitStatic("back_video", self)
	xml:InitStatic("background", self)
	xml:InitStatic("rug_video", self)
	
	self.dialog = xml:InitStatic("main_dialog:dialog", self)
	xml:InitStatic("main_dialog:cap_cheat", self.dialog)
	
	xml:InitFrame("main_dialog:frame",	self.dialog)
	
	self.tab = xml:InitTab("main_dialog:tab", self.dialog)
	self:Register(self.tab,	"tab")
	
	xml:InitFrame("main_dialog:list_frame",			self.dialog)
	self.list = xml:InitList("main_dialog:list_window", 	self.dialog)
	self.list:ShowSelectedItem(true)
	self:Register(self.list, "list_window")
	self.subCapt = xml:InitStatic("main_dialog:caption_list", self.dialog)
	
	local ctrl
	ctrl = xml:Init3tButton("main_dialog:btn_spawn", self.dialog)
	ctrl:Enable(ui_cheat_main.check_game()==true)
	self:Register(ctrl, "btn_spawn")
	ctrl = xml:Init3tButton("main_dialog:btn_cancel", self.dialog)
	self:Register(ctrl, "btn_cancel")
	-- Поиск по имени
	self.edit_box = xml:InitEditBox("main_dialog:frame_search",	self.dialog)
	self.search = CUIStatic()
	self.search:SetWindowName("search")
	self.search:SetAutoDelete(true)
	self.search:SetText("Поиск")
	self.search:SetTextColor(255,0,255,0)
	self.search:SetFont(GetFontLetterica18Russian())
    self.search:Init(745,310,134,23)
    self:AttachChild(self.search)
	
	self.text = ""
	-- переключение раскладки клавиатуры (EN/RU)
	self.lang = "RUS"
	self.btn_lang = CUIButton()
	self.btn_lang:Init("ui\\ui_hud",913,308,37,25)
	self.btn_lang:SetText(self.lang)
	self.btn_lang:SetTextAlign(CGameFont.alCenter)
	self.btn_lang:SetTextY(1)
	self.btn_lang:SetTextColor(255,240,165,25)
	self.btn_lang:SetOriginalRect(65,704,37,25)
	self:Register(self.btn_lang, "btn_lang")
	self:AttachChild(self.btn_lang)
	self:AddCallback("btn_lang", ui_events.BUTTON_DOWN, self.ClickBtnLang, self)
	
	self.section_name = xml:InitStatic("main_dialog:sect_wnd", self.dialog)
	-- Описание
	xml:InitFrame("description:frame_descr", self)
	xml:InitStatic("description:caption_descr", self)
	self.scroll_v = xml:InitScrollView("description:scroll_v", self)
	
	local _st
	_st = xml:InitStatic("description:templ_item", self.scroll_v)
	self.cost = xml:InitStatic("description:cost_wnd", _st)
	_st = xml:InitStatic("description:templ_item", self.scroll_v)
	self.weight = xml:InitStatic("description:weight_wnd", _st)
	_st = xml:InitStatic("description:templ_item", self.scroll_v)
	_st:SetHeight(2300)
	self.descr = xml:InitStatic("description:descr_list", _st)
	
	self:LoadCaption()
end

function cheat_menu:InitCallBacks()
	self:AddCallback("tab",				ui_events.TAB_CHANGED,				self.OnTabChange,			self)
	self:AddCallback("btn_cancel",		ui_events.BUTTON_CLICKED,			self.OnBtnCancel,			self)
	self:AddCallback("btn_spawn",		ui_events.BUTTON_CLICKED,			self.OnBtnSpawn,			self)
	self:AddCallback("list_window",		ui_events.LIST_ITEM_CLICKED, 		self.OnListItemClicked,		self)
	self:AddCallback("list_window",		ui_events.WINDOW_LBUTTON_DB_CLICK,	self.OnListItemDbClicked,	self)
end

function cheat_menu:OnBtnCancel()
	self:GetHolder():start_stop_menu	(self.owner, true) --new(show main window)
	self:GetHolder():start_stop_menu	(self,true)
	self.owner:Show						(true)
end

function cheat_menu:OnTabChange()
	local i = self.tab:GetActiveIndex()
	self.menu_index = i+1
	
	local x1 = 0
	local x2 = 0
	local y1 = i>=4 and 0 or 28
	local y2 = i>=4 and 28 or 0
	for a=0,self.tab:GetTabsCount()-1 do
		local btn = self.tab:GetButtonByIndex(a)
		if a>=4 then
			btn:SetWndPos(x2,y2)
			x2 = x2+116
		else
			btn:SetWndPos(x1,y1)
			x1 = x1+116
		end
	end
	
	self:FillList()
	self:LoadCaption()
	self:OnListItemClicked()
	
	local itm_index = self.list:GetSelectedItem()
	if itm_index then self.list:ScrollToPos(itm_index) end
end

function cheat_menu:LoadCaption()
	local names = {"оружие","боеприпасы","аддон","броню","артефакт"}
	self.subCapt:SetText("Выберите "..(names[self.menu_index] or "предмет")..":")
end

function cheat_menu:OnListItemClicked()
	if self.list:GetSize()==0 then return end
	
	local itm_index = self.list:GetSelectedItem()
	if itm_index < 0 or #self.tbl<itm_index+1 then return end
	local itm = self.list:GetItem(itm_index)
	if itm == nil then return end
	
	
	local sect = itm.sct:GetText()
	local sizes = ui_cheat_main.give_icon_params(sect)
	
	local pw = (sizes.width/5)*4
	local ph = (sizes.height/5)*4
	local px = 725-(pw/2)
	local py = 400-(ph/2)
	
	if self.pict==nil then
		self.pict = CUIStatic()
		self.pict:SetWindowName("pict")
		self.pict:SetAutoDelete(true)
		self:AttachChild(self.pict)
	end
	self.pict:InitTexture("ui\\ui_icon_equipment")
	self.pict:InitTexture("ui\\ui_icon_equipment_1")
	self.pict:InitTexture("ui\\ui_icon_equipment_2")
	self.pict:InitTexture("ui\\ui_icon_equipment_3")
	self.pict:InitTexture("ui\\ui_icon_equipment_4")
	self.pict:InitTexture("ui\\ui_icon_equipment_5")
	self.pict:InitTexture("ui\\ui_icon_equipment_6")
	self.pict:InitTexture("ui\\ui_icon_equipment_7")
	self.pict:SetOriginalRect(sizes.x,sizes.y,sizes.width,sizes.height)
	self.pict:Init(px,py,pw,ph)
	self.pict:SetStretchTexture(true)
	
	local description = ui_cheat_main.read_if_exist("str", sect, "description", "%c[255,255,0,0]<no description>")
	local cst = ui_cheat_main.read_if_exist("flt", sect, "cost", 0)
	local wght = ui_cheat_main.read_if_exist("flt", sect, "inv_weight", 0)
	self.descr:SetText(game.translate_string(description))
	self.cost:SetText(string.format("Цена: %d руб.", cst))
	self.weight:SetText(string.format("Вес: %.2f кг.", wght))
	self.scroll_v:ScrollToBegin()
	self.section_name:SetText(sect)
end

function cheat_menu:OnListItemDbClicked()
	self:OnBtnSpawn()
end

function cheat_menu:ClickBtnLang()
	self.lang = (self.lang == "RUS" and "ENG") or "RUS"
	self.btn_lang:SetText(self.lang)
end

function cheat_menu:SearchText(letter)
	local lett = letter and (self.lang=="RUS" and self.translit[letter] or letter) or ""
	if string.len(self.text)>=18 then return end
	self.text = self.text..lett
	
	self.search:SetText(self.text)
	self:SearchItem()
end

function cheat_menu:BackSpace()
	if self.text ~= "" and string.len(self.text)>1 then
		self.text = string.sub(self.text,1,string.len(self.text)-1)
		self.search:SetText(self.text)
	else
		self.text = ""
	end
	self.search:SetText(self.text)
end

function cheat_menu:SearchItem()
	if self.text == "" then return end
	local size = self.list:GetSize()
	local search_text = ui_cheat_main.string_lower(self.text)
	search_text = string.gsub(search_text,"-"," ")
	for i=0,size-1 do
		local item = self.list:GetItem(i)
		local item_text = ui_cheat_main.string_lower(item.fn:GetText())
		item_text = string.gsub(item_text,"-"," ")
		item_text = string.gsub(item_text,"ё","е")
		if #item_text>=#search_text and string.find(item_text,search_text) then
			self.list:ScrollToPos(i)
			break
		end
	end
end

function cheat_menu:OnBtnSpawn()
	if self.list:GetSize()==0 then return end
	local itm_index = self.list:GetSelectedItem()
	if (not itm_index) or itm_index < 0 then return end

	local itm = self.list:GetItem(itm_index)
	if itm == nil then return end
	local sect = itm.sct:GetText()
	ui_cheat_main.spawn_item(sect)
end

function cheat_menu:OnKeyboard(dik, keyboard_action)
	CUIScriptWnd.OnKeyboard(self,dik,keyboard_action)
	if keyboard_action == ui_events.WINDOW_KEY_PRESSED then
		if dik == DIK_keys.DIK_ESCAPE then self:OnBtnCancel()
		elseif dik == DIK_keys.DIK_RETURN then self:OnBtnSpawn()
		elseif dik == DIK_keys.DIK_TAB then self:OnKeyNewTab()
		elseif dik == DIK_keys.DIK_BACK then self:BackSpace()
		else
			local letter = string.sub(self.edit_box:GetText(),-1)
			if letter and letter~="" then
				self:SearchText(letter)
				self.edit_box:SetText("")
			end
		end
	end
	return true
end

function cheat_menu:OnKeyNewTab()
	local i = self.tab:GetActiveIndex()
	local cnt = self.tab:GetTabsCount()
	local new_tab = i==cnt-1 and 0 or i+1
	self.tab:SetNewActiveTab(new_tab)
	self:OnTabChange()
end

function cheat_menu:AddItemToList(sect)
--	if ui_cheat_main.check_item(sect) == false then return end
	
	local itm_name = game.translate_string(ui_cheat_main.read_if_exist("str", sect, "inv_name", sect))
	-- Если вещь квестовая - напишем об этом
	if ui_cheat_main.read_if_exist("bln", sect, "quest_item", false) == true
			or ui_cheat_main.read_if_exist("bln", sect, "can_trade", true) == false then
		itm_name = itm_name.." (квестовый)"
	end
	
	if string.len(itm_name)>50 then itm_name = string.sub(itm_name,1,50).."..." end
	
	local _itm = load_item()
	_itm.fn:SetText(itm_name)
	_itm.sct:SetText(sect)
	self.list:AddItem		(_itm)
end
------------------------------------------------------------------------------------------
class "load_item" (CUIListItemEx)

function load_item:__init() super()
	self:SetWndRect		(0,0,430,22)
	
	self.fn					= CUIStatic	()
	self.fn:SetAutoDelete	(true)
	self:AttachChild		(self.fn)
	self.fn:SetWndRect		(0,0,230,22)
	self.fn:SetText			("name")
	self.fn:SetFont			(GetFontLetterica16Russian())
	self.fn:SetTextColor	(255,255,234,104)
	
	self.sct				= CUIStatic	()
	self.sct:SetAutoDelete	(true)
	self:AttachChild		(self.sct)
	self.sct:SetWndRect		(230,0,200,22)
	self.sct:SetText		("section")
	self.sct:SetFont		(GetFontLetterica16Russian())
	self.sct:SetTextColor	(0,0,0,0)
end
