section = "af_dummy_black_tip"
last_id = false
info    = "info_black_tip" 

function attach(sm)
  sm:subscribe({signal = "on_init_modules", fun = this.init_module})
  sm:subscribe({signal = "on_late_init_all", fun = this.late_init})
--   sm:subscribe({signal = "on_before_save_game", fun = this.on_before_save})
end

function have_black_tip()
	return sak_inventory.rucksack[section] or
        sak_inventory.belt_items[section] or
        arc_containers.inv_containers:have_black_tip()
end  

function need_black_tip()
	return db.actor:has_info(info) and get_value("catched_bt")
end

function black_tip.discharge(coef)
	if level.name()=="aver" then return end
  
	if not need_black_tip() then return end
    
	local list = have_black_tip()  
  
	if type(list) ~= 'table' then
		if arc_containers.inv_containers:have_black_tip() then
			wprintf("[~T].~C0B #HINT: ЧМ спрятана в контейнер и не разрушается ~C07")
			return 
		end                          
		on_drop(last_id)
		return 
	end
  
	local act = db.actor
	local act_pos = act:position()

	local is_gg_away = true
	for _,v in pairs(db.creatures) do
		if v and v:is_stalker() and v:alive() then
			local com = v:character_community()
			if com ~= "zombied" then
				if v:position():distance_to(act_pos) < 100 then
					is_gg_away = false
					-- log2("black_tip.discharge: is_gg_away set to false due to npc nearby [%s]",v:name())
					break
				end
			end
		end
	end
	if not is_gg_away then
		-- log2("black_tip.discharge: setting low coef, someone is nearby")
		coef = tonumber(coef) * 0.3
	else
		-- log2("black_tip.discharge: setting high coef, noone is nearby")
	end
	
	for i, id in ipairs (list) do    
		local cv = params.add_condition(id, -0.004 * tonumber(coef))
		-- обработка вредной ЧМ, удаление лишних копий
		wprintf("~C06 black tip~C0D %d~C07 discharge, condition =~C0F %.5f~C07", id, cv or -1)      
		if (cv >= 0) and (cv < 0.15) or (i > 1) then
			wprintf(" внезапно кончилась ЧМ~C0D %d~C07, с износом =~C0D %.3f~C07", id, cv)
			misc.release_obj(id, 'defeat black tip')
			if i == 1 then 
				act:disable_info_portion ("info_black_tip")
				remove_value("catched_bt")
				xr_statistic.add_pts("otherstats", "st_pda_otherstats_black_tip", 1, 50.0)
				local prize = misc.spawn_to ("af_dummy_simbion", act)
				if prize then
					local r = lua_random(50,75) * 0.01
					params.post_cond_check(prize.id,r)
					sak.send_tip(game.translate_string("black_tip_sms_1"),game.translate_string("black_tip_sms_1_h"),3,15,"teleport","sak","red")
				end
			end    
			set_value("black_off", 0.8)
			break     
		end
		last_id = id    
		set_value("catched_bt", id)
	end
end


function check_dropped(obj)
	if obj:section() == section and need_black_tip() then  
		wprintf(" detected drop very important object~C0F %s ~C07", obj:name())
		on_drop(obj:id()) 
		return true
	end     
	return false
end


function black_tip.respawn(id)  
	if have_black_tip() or not need_black_tip() then return end   
	local objs = {}

	for i, sobj in alife():objects() do
		if sobj and sobj:section_name() == section then
			objs[i] = sobj
		end
	end

	for i, sobj in pairs(objs) do
		if sobj.parent_id == 0 then
			wprintf("[~T].~C0B #HAPPY:~C06 ЧМ найдена у законного владельца~C0A %s~C07", sobj:name())
			sak_inventory.need_update_inventory()
			health_handle()
			return  
		elseif sobj.level_name == level.name() then
			wprintf("[~T].~C06 #DBG: обнаружена подходящая для возвращения ЧМ~C0D %d ~C07", sobj.id)
			g_sim:set_switch_online  (sobj.id, true)
			g_sim:set_switch_offline (sobj.id, false)     
			schedule.add("myaso", sprintf("sak.actor_pickup(%d, black_tip.respawn())", sobj.id), lua_random(500, 1500))
			return
		elseif sobj.parent_id ~= 0 then
			wprintf("[~T].~C06 #DBG: обнаружена подходящая для уничтожения ЧМ, у владельца~C0D %d~C06 на уровне~C0A %s~C07", sobj.parent_id, sobj.level_name) 
			misc.release_obj(sobj, 'black_tip.respawn0')
		end
	end

	amk.spawn_item_in_inv(section) -- новая метка, без повреждений
	if not id then return end 
	local obj = g_sim:object(tonumber(id))
	if obj then
		misc.release_obj(obj, 'black_tip.respawn')
	end
end

function black_tip.on_drop(id)
	id = tonumber(id or 0) 
	if id == 0 then
		respawn (false)
		return 
	end                  
  
	local obj = client_obj(id)
	if obj then
		local pobj = obj:parent()
		if pobj and pobj.is_alive then    
			if pobj:id() ~= 0 then 
				wprintf("[~T].~C0B #HAPPY:~C06 ЧМ перешла к другой жизненной форме~C0A %s~C07", pobj:name())
				db.actor:disable_info_portion ("info_black_tip")
			end   
			return
		end
      
		wprintf("~C0C наверное потерялась ЧМ ~C0D %s~C0C =~C0F %s~C07, будем поискать~C07", DumpVar(id), obj:name())
		if lua_random() < 0.5 then
			schedule.add("myaso_need", sprintf("sak.actor_pickup(%d, black_tip.on_drop(0))", id), lua_random(1000, 3000))
		end    
		return 
	end  
    
	obj = g_sim:object(id)
	if obj then
		wprintf("[~T]. #DBG: ЧМ уничтожена физически, наверное надо респавн")
		timers.start_timer("black_tip", lua_random(10,60),"black_tip.respawn("..id..")")
		return
	end
end


function black_tip.health_handle()
	local bt = have_black_tip()
	if not bt then return end
	if type(bt) == "table" then bt = bt[1] end
	set_value("catched_bt", bt)
   
	if not need_black_tip() then
		db.actor:give_info_portion(info)
	end   
     
	local act = db.actor
	local life_hack = has_alife_info("black_tip_general_info")
	n_healh = act.health
	s_healh = params.actor_satiety_health()
	local pwr_restore = (life_hack and params.pwr_restore) or 0
	local dog_shield = (life_hack and bind_monster.dog_shield) or 1
	-- log2("black_tip.health_handle: pwr_restore [%.4f] dog_shield [%.4f]", pwr_restore, dog_shield)
	
	local cond = 1
	if type(bt) == "number" then
		cond = params.get_condition(bt) or 1
		-- log2("black_tip.health_handle: using condition coef = %.3f", cond)
	end
	
	if n_healh >= 0.4 then params.health_add  (-0.05 * cond) end
	if s_healh >= 0.2 then
		if life_hack and sak.arts_operate == true and sak_inventory.belt_items["af_flower_new"] then
			arc_arts.discharge_art_on_belt( "af_flower_new", 0.0001 )
		else
			params.satiety_add (-0.005 * cond)
		end
	end
	if lua_random() < 0.2 then
		level.add_pp_effector("black_tip_eff.ppe", 1031, false)
		local r = lua_random()
		if r < ( 0.2 * dog_shield ) then
			vergas_lib.s_play(sak.pain_snd_tbl[lua_random(#sak.pain_snd_tbl)],1)
			level.add_cam_effector("camera_effects\\fusker.anm", 999, false, "")
			level.add_pp_effector("amk_shoot.ppe", 2011, false)
			set_inactivate_input_time(20)
			local active_item = act:active_item()
			if active_item and active_item:section()~="bolt" and active_item:get_slot() ~= 7 then
				act:drop_item(active_item)
			end
		elseif r < 0.3 then
			if life_hack and get_value("block_sleep_menu") ~= nil and get_value("block_sleep_menu") > 0 then
				return
			end
			vergas_lib.s_play([[affects\tinnitus3a]])
			sak.fake_vodka_drink()
		elseif r < 0.4 then
			get_actor_obj().condition:set_force_next_jam(true)
		elseif r < 0.6 - pwr_restore then
			if db.actor.power > 0.5 then
				db.actor.power = -0.5
			end
		end
	end
end

function init_module()
end

function late_init()
	black_tip.discharge(0)
end
